# Generated by Django 3.0.5 on 2021-04-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_code', models.CharField(max_length=3)),
                ('destination_picture', models.BinaryField(blank=True, null=True)),
                ('website_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'destination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller_id', models.IntegerField()),
                ('dest_id', models.IntegerField()),
            ],
            options={
                'db_table': 'favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller_id', models.IntegerField()),
                ('friend_id', models.IntegerField()),
                ('date_of_friendship', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'friend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=1025)),
                ('address', models.CharField(blank=True, max_length=1025, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.BinaryField(blank=True, null=True)),
                ('credit_card_info', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'traveler',
                'managed': False,
            },
        ),
    ]
